% Script that adds the study areas in a plot.

%%%%%%%%%%%%%%%
%%% LOADING %%%
%%%%%%%%%%%%%%%
box_lims                                       % Contains lat and lon limits for plotting areas


%%%%%%%%%%%%%%%%
%%% Plotting %%%
%%%%%%%%%%%%%%%%

%%% Figure 1 - Surface reflectance 2004-2008
% Setting Axes and Projection

%forestbox:
box1 = linem([max(landeslims.forestbox.latlim); min(landeslims.forestbox.latlim);...
    min(landeslims.forestbox.latlim); max(landeslims.forestbox.latlim);...
    max(landeslims.forestbox.latlim)], [min(landeslims.forestbox.lonlim);...
    min(landeslims.forestbox.lonlim); max(landeslims.forestbox.lonlim);...
    max(landeslims.forestbox.lonlim); min(landeslims.forestbox.lonlim)],...
    'Color',[1 0 0], 'LineWidth', 2);

% nonforest1:
box2 = linem([max(landeslims.nonforbox1.latlim); min(landeslims.nonforbox1.latlim);...
    min(landeslims.nonforbox1.latlim); max(landeslims.nonforbox1.latlim);...
    max(landeslims.nonforbox1.latlim)], [min(landeslims.nonforbox1.lonlim);...
    min(landeslims.nonforbox1.lonlim); max(landeslims.nonforbox1.lonlim);...
    max(landeslims.nonforbox1.lonlim); min(landeslims.nonforbox1.lonlim)],...
    'Color',[0 0 1], 'LineWidth', 2);

% nonforest2:
box3 = linem([max(landeslims.nonforbox2.latlim); min(landeslims.nonforbox2.latlim);...
    min(landeslims.nonforbox2.latlim); max(landeslims.nonforbox2.latlim);...
    max(landeslims.nonforbox2.latlim)], [min(landeslims.nonforbox2.lonlim);...
    min(landeslims.nonforbox2.lonlim); max(landeslims.nonforbox2.lonlim);...
    max(landeslims.nonforbox2.lonlim); min(landeslims.nonforbox2.lonlim)],...
    'Color',[0 0 1], 'LineWidth', 2);

l = legend([box1 box2 box3], 'Forest','Nonforest1', 'Nonforest2','Location','eastoutside');